import 'package:flutter_test/flutter_test.dart';
import 'package:html/dom.dart';
import 'package:ingredient_collector/src/models/ingredient.dart';
import 'package:ingredient_collector/src/models/recipe_parsing_job.dart';
import 'package:ingredient_collector/src/recipe_controller.dart';
import 'package:ingredient_collector/src/recipe_scripts/eat_this.dart';

import 'script_test_helper.dart';

void main() {
  test(
    'collect new Eat this! recipe',
    () async {
      var recipeJob = RecipeParsingJob(
        url: Uri.parse(
          "https://www.eat-this.org/planetary-health-bowl-mit-lupinen-und-kurkuma-dressing/",
        ),
        servings: 2,
        language: "de",
      );

      var result = await collectRecipes([recipeJob], "de");
      expect(result.length, 1);
      expect(hasRecipeParsingErrors(result.first), isFalse);

      var recipe = result.first.recipe!;
      expect(recipe.servings, 2);
      expect(recipe.ingredients.length, 23);

      expectIngredient(recipe, "Sonnenblumenkerne", amount: 60, unit: "g");
      expectIngredient(recipe, "Zitrone", amount: 0.5);
      expectIngredient(recipe, "Kurkumapulver", amount: 1.5, unit: "TL");
      expectIngredient(recipe, "Ingwerpulver", amount: 1.5, unit: "TL");
      expectIngredient(recipe, "Apfelessig", amount: 2, unit: "EL");
      expectIngredient(recipe, "Apfeldicksaft", amount: 1.5, unit: "TL");
      expectIngredient(recipe, "Salz", amount: 1, unit: "TL");
      expectIngredient(recipe, "Schalotte", amount: 1);
      expectIngredient(recipe, "Rote Bete", amount: 150, unit: "g");
      expectIngredient(recipe, "Karotte", amount: 120, unit: "g");
      expectIngredient(recipe, "Apfel", amount: 60, unit: "g");
      expectIngredient(recipe, "Leinöl", amount: 1.5, unit: "EL");
      expectIngredient(recipe, "Apfelessig", amount: 1, unit: "EL");
      expectIngredient(recipe, "Pastinake", amount: 250, unit: "g");
      expectIngredient(recipe, "braune Champignons", amount: 250, unit: "g");
      expectIngredient(recipe, "Rapsöl", amount: 2, unit: "EL");
      expectIngredient(recipe, "Salz", amount: 0.75, unit: "TL");
      expectIngredient(recipe, "Buchweizen", amount: 125, unit: "g");
      expectIngredient(recipe, "Feldsalat", amount: 100, unit: "g");
      expectIngredient(recipe, "gekochte Lupinen", amount: 200, unit: "g");
      expectIngredient(recipe, "Sauerkraut", amount: 60, unit: "g");
      expectIngredient(recipe, "Walnüsse", amount: 25, unit: "g");
      expectIngredient(recipe, "Microgreens", amount: 20, unit: "g");
    },
    tags: ["parsing-test"],
  );

  test(
    'collect old Eat this! recipe',
    () async {
      var recipeJob = RecipeParsingJob(
        url: Uri.parse(
          "https://www.eat-this.org/gruner-bohnensalat-mit-speck/",
        ),
        servings: 4,
        language: "de",
      );

      var result = await collectRecipes([recipeJob], "de");
      expect(result.length, 1);
      expect(hasRecipeParsingErrors(result.first), isFalse);

      var recipe = result.first.recipe!;
      expect(recipe.servings, 4);
      expect(recipe.ingredients.length, 13);

      expectIngredient(recipe, "grüne Buschbohnen", amount: 750, unit: "g");
      expectIngredient(recipe, "Räuchertofu", amount: 400, unit: "g");
      expectIngredient(recipe, "Frühlingszwiebeln", amount: 2.5);
      expectIngredient(recipe, "Tomaten", amount: 2);
      expectIngredient(recipe, "Öl zum anbraten", amount: 1, unit: "EL");
      expectIngredient(recipe, "Sonnenblumenöl", amount: 4, unit: "EL");
      expectIngredient(recipe, "würziger Essig", amount: 4, unit: "EL");
      expectIngredient(recipe, "Zitronensaft", amount: 1, unit: "EL");
      expectIngredient(recipe, "Sojasauce", amount: 1, unit: "EL");
      expectIngredient(recipe, "Agavendicksaft", amount: 1, unit: "EL");
      expectIngredient(recipe, "Zucker", amount: 1, unit: "EL");
      expectIngredient(recipe, "Knoblauchzehe", amount: 1);
      expectIngredient(recipe, "Salz + Pfeffer, wie immer");
    },
    tags: ["parsing-test"],
  );

  test(
    'collect many new Eat this! recipes',
    () async {
      await testParsingRecipes(_testUrlsNewRecipes);
    },
    tags: ["parsing-test"],
    timeout: const Timeout(Duration(minutes: 10)),
  );

  test(
    'collect many old Eat this! recipes',
    () async {
      await testParsingRecipes(_testUrlsOldRecipes);
    },
    tags: ["parsing-test"],
    timeout: const Timeout(Duration(minutes: 10)),
  );

  test('parse empty ingredient element new design', () {
    var ingredientElement = Element.html("<a></a>");
    var result = parseIngredientNewDesign(ingredientElement, 1, "");
    expect(hasIngredientParsingErrors(result), isTrue);
  });

  test('parse empty ingredient element old design', () {
    var ingredientElement = Element.html("<a></a>");
    var result = parseIngredientOldDesign(ingredientElement, 1, "");
    expect(hasIngredientParsingErrors(result), isTrue);
  });

  test('parse ingredient element new design', () {
    var ingredientElement = Element.html("""
    <li class="wprm-recipe-ingredient">
      <span class="wprm-recipe-ingredient-amount">½</span>
      <span class="wprm-recipe-ingredient-unit">TL</span>
      <span class="wprm-recipe-ingredient-name">Zucker</span>
    </li>
    """);
    var result = parseIngredientNewDesign(ingredientElement, 1, "");
    expect(hasIngredientParsingErrors(result), isFalse);
    expect(
      result.ingredients[0],
      equals(
        const Ingredient(
          amount: 0.5,
          unit: "TL",
          name: "Zucker",
        ),
      ),
    );
  });

  test('parse ingredient element old design', () {
    var ingredientElement = Element.html("""
    <li>
      1 1/2 EL Reis- oder Ahornsirup
    </li>
    """);
    var result = parseIngredientOldDesign(ingredientElement, 1, "");
    expect(hasIngredientParsingErrors(result), isFalse);
    expect(
      result.ingredients[0],
      equals(
        const Ingredient(
          amount: 1.5,
          unit: "EL",
          name: "Reis- oder Ahornsirup",
        ),
      ),
    );
  });

  test('provide feedback when amount parsing fails', () {
    var ingredientElement = Element.html("""
    <li class="wprm-recipe-ingredient">
      <span class="wprm-recipe-ingredient-amount">amount</span>
      <span class="wprm-recipe-ingredient-name">Blumenkohl</span>
    </li>
    """);
    var result = parseIngredientNewDesign(ingredientElement, 1, "");
    expect(hasIngredientParsingErrors(result), isTrue);
  });
}

const _testUrlsNewRecipes = <String>[
  "https://www.eat-this.org/veganer-borschtsch/",
  "https://www.eat-this.org/vegane-skoleboller-norwegische-puddingteilchen/",
  "https://www.eat-this.org/geschmorter-fenchel-mit-zitronen-couscous/",
  "https://www.eat-this.org/veganer-colcannon-irischer-kartoffelbrei/",
  "https://www.eat-this.org/vegane-miso-carbonara-mit-tempeh-speck/",
  "https://www.eat-this.org/vegane-jaegersauce/",
  "https://www.eat-this.org/herzhafte-vegane-erbsensuppe/",
  "https://www.eat-this.org/vegane-teriyaki-krautwickel-japanisch-inspirierte-wirsingrouladen/",
  "https://www.eat-this.org/cremige-ofen-gnocchi-mit-bohnen-brokkoli/",
  "https://www.eat-this.org/buddhistische-fastenspeise-buddhas-delight/",
  "https://www.eat-this.org/bibimbap-pasta-oder-bibim-pasta/",
  "https://www.eat-this.org/bohnenstampf-mit-chili-wirsing/",
  "https://www.eat-this.org/knoedel-auflauf-mit-veganer-winter-bolognese/",
  "https://www.eat-this.org/vegane-kimchi-pizza-schnecken/",
  "https://www.eat-this.org/vegane-mini-chai-lebkuchen/",
  "https://www.eat-this.org/veganer-orangen-filo-kuchen-portokalopita/",
  "https://www.eat-this.org/vegane-walnuss-panna-cotta-mit-schokoladen-ganache/",
  "https://www.eat-this.org/vegane-spitzbuben/",
  "https://www.eat-this.org/vegane-fondant-kartoffeln/",
  "https://www.eat-this.org/selbst-gemachte-mock-duck/",
  "https://www.eat-this.org/vegane-maronensuppe-mit-pumpernickel-granola/",
  "https://www.eat-this.org/wildreissuppe-mit-kuerbis-pilzen/",
  "https://www.eat-this.org/vegane-doppel-schoko-muffins-mit-banane-haselnuss/",
  "https://www.eat-this.org/pastinaken-sellerie-suppe-mit-apfel-kapern-topping/",
  "https://www.eat-this.org/vegane-mohnschnecken/",
  "https://www.eat-this.org/karamellisierte-zwiebel-pasta/",
  "https://www.eat-this.org/vegane-brokkoli-lauch-galette/",
  "https://www.eat-this.org/veganer-pastitsio-die-griechische-lasagne/",
  "https://www.eat-this.org/chinesisches-kartoffel-stir-fry/",
  "https://www.eat-this.org/linguine-mit-geroestetem-kuerbis-und-salbei/",
  "https://www.eat-this.org/gemuesebruehe-aus-gemueseresten/",
  "https://www.eat-this.org/vegane-brezenknoedel-mit-pilzrahmsauce/",
  "https://www.eat-this.org/tuerkische-stangenbohnen-in-tomatensauce/",
  "https://www.eat-this.org/bruschetta-pasta/",
  "https://www.eat-this.org/vegane-zwetschgenknoedel-mit-kartoffelteig/",
  "https://www.eat-this.org/auberginen-pilaf-mit-veganem-grillkaese/",
  "https://www.eat-this.org/muhammara-walnuss-paprika-dip/",
  "https://www.eat-this.org/vegane-maispuffer-mit-gochujang/",
  "https://www.eat-this.org/veganer-heringssalat-mit-roter-bete-raeuchertofu/",
  "https://www.eat-this.org/vegane-arabische-pasta-mit-joghurtsauce/",
  "https://www.eat-this.org/artischocken-zitronen-pasta/",
  "https://www.eat-this.org/wassermelonen-gurkensalat-mit-chilioel/",
  "https://www.eat-this.org/veganer-wassermelonen-thunfisch/",
  "https://www.eat-this.org/veganer-fatteh-mit-auberginen-und-brokkoli/",
  "https://www.eat-this.org/vegane-snickers-reiswaffeln/",
  "https://www.eat-this.org/vegane-vietnamesische-pizza-banh-trang-nuong/",
  "https://www.eat-this.org/brokkolisuppe-mit-orzo/",
  "https://www.eat-this.org/veganer-limburger-mit-musik/",
  "https://www.eat-this.org/vegane-hoagie-rolls-sandwichbrot/",
  "https://www.eat-this.org/vegane-erdbeer-mousse-mit-aquafaba/",
  "https://www.eat-this.org/vegane-thailaendische-fischfrikadellen-tod-mun-pla/",
  "https://www.eat-this.org/veganer-geburtstagskuchen-mit-schoko-frosting/",
  "https://www.eat-this.org/vegane-spargelcremesuppe-mit-zitronengras/",
  "https://www.eat-this.org/gruenkern-hackbaellchen-mit-senf-spargelragout/",
  "https://www.eat-this.org/vegane-kaesespaetzle/",
  "https://www.eat-this.org/lauchspaghetti-pasta-con-porro/",
  "https://www.eat-this.org/veganer-lachs-aus-tofu/",
  "https://www.eat-this.org/vegane-hot-cross-buns/",
  "https://www.eat-this.org/vegane-bananen-tarte-tatin-mit-miso-karamell/",
  "https://www.eat-this.org/baerlauch-erbsensuppe-mit-tahin-und-rauchmandeln/",
  "https://www.eat-this.org/vegane-harira-marokkanische-kichererbsensuppe/",
  "https://www.eat-this.org/veganes-schlemmerfilee-mit-rote-bete-meerrettich-pueree/",
  "https://www.eat-this.org/veganes-erdnuss-curry-mit-jackfruit/",
  "https://www.eat-this.org/vegane-fruehlingszwiebel-waffeln/",
  "https://www.eat-this.org/einfaches-knoblauch-confit/",
  "https://www.eat-this.org/griechische-bohnenbaellchen-mit-zitronen-oliven-orzo/",
  "https://www.eat-this.org/vegane-spaghetti-cacio-e-pepe/",
  "https://www.eat-this.org/vegane-dan-dan-nudeln/",
  "https://www.eat-this.org/unser-einfaches-congee/",
  "https://www.eat-this.org/veganes-japanisches-milchbrot-shokupan/",
  "https://www.eat-this.org/die-perfekte-selbst-gemachte-falafel/",
  "https://www.eat-this.org/vegane-funfetti-donuts-aus-dem-ofen/",
  "https://www.eat-this.org/veganes-katsu-sando-die-japanische-schnitzelsemmel/",
  "https://www.eat-this.org/geroestete-blumenkohl-knoblauch-suppe-mit-kichererbsen/",
  "https://www.eat-this.org/rotwein-spaghetti-mit-kraeuter-nuss-pangrattato/",
  "https://www.eat-this.org/veganes-biryani-mit-tofu/",
  "https://www.eat-this.org/lotuswurzel-suesssauer/",
  "https://www.eat-this.org/chinesischer-home-style-tofu/",
  "https://www.eat-this.org/vegane-gruene-enchiladas/",
  "https://www.eat-this.org/vegane-blumenkohl-bolognese-mit-champignons/",
  "https://www.eat-this.org/blumenkohl-polenta-baellchen-mit-chili-joghurt/",
  "https://www.eat-this.org/geroesteter-gochujang-rosenkohl/",
  "https://www.eat-this.org/vegane-gruenkohl-bohnen-minestrone/",
  "https://www.eat-this.org/kitchari-indisches-reis-porridge/",
  "https://www.eat-this.org/vegane-pasta-e-fagioli/",
  "https://www.eat-this.org/grapefruit-ginger-rum-highball/",
  "https://www.eat-this.org/veganer-cheesecake-apfelstrudel/",
  "https://www.eat-this.org/vegane-seidene-kloesse/",
  "https://www.eat-this.org/veganer-sauerbraten-auf-fraenkische-art/",
  "https://www.eat-this.org/apfel-fenchel-salat-mit-veganem-blauschimmelkaese/",
  "https://www.eat-this.org/veganes-pilz-stroganoff/",
  "https://www.eat-this.org/schnelle-cremige-tofu-nudeln/",
  "https://www.eat-this.org/belegte-fladenbrote-mit-geroesteten-harissa-kichererbsen-und-rote-bete/",
  "https://www.eat-this.org/veganer-brotauflauf/",
  "https://www.eat-this.org/vegane-donauwelle/",
  "https://www.eat-this.org/gebratener-radicchio-auf-weissem-bohnenmus/",
  "https://www.eat-this.org/veganes-haehnchengeschnetzeltes-mit-pilzen/",
  "https://www.eat-this.org/vegane-jalapeno-popper-mumien/",
  "https://www.eat-this.org/schnelle-erdnussbutter-nudeln/",
  "https://www.eat-this.org/one-pot-kuerbis-pasta/",
  "https://www.eat-this.org/vegane-pfannkuchen-mit-spinatfuellung/",
  "https://www.eat-this.org/veganes-pad-see-ew-thailaendische-gebratene-reisnudeln/",
  "https://www.eat-this.org/veganer-banoffee-pie/",
  "https://www.eat-this.org/geschmorter-kuerbis-mit-miso/",
  "https://www.eat-this.org/vegane-kartoffelcremesuppe-mit-brezel-croutons/",
  "https://www.eat-this.org/veganer-leberkaese/",
  "https://www.eat-this.org/vegane-germknoedel-mit-zwetschgenmus/",
  "https://www.eat-this.org/veganer-wurstsalat-auf-bayrische-art/",
  "https://www.eat-this.org/geroesteter-gemuesesalat-mit-weissen-riesenbohnen/",
  "https://www.eat-this.org/vegane-pasta-alla-norma/",
  "https://www.eat-this.org/vegane-pizza-bianca-mit-spinat/",
  "https://www.eat-this.org/veganer-ricotta-aus-mandeln/",
  "https://www.eat-this.org/veganer-bienenstich/",
  "https://www.eat-this.org/vegane-pfirsich-tarte-tatin/",
  "https://www.eat-this.org/japanisches-donburi-mit-geschmorter-aubergine/",
  "https://www.eat-this.org/blumenkohl-champignonpfanne-mit-mafaldine/",
  "https://www.eat-this.org/unser-liebstes-tofu-stir-fry/",
  "https://www.eat-this.org/corn-ribs-gegrillter-mais/",
  "https://www.eat-this.org/einfache-seitan-gyrospfanne/",
  "https://www.eat-this.org/lib-el-kousa-zucchini-knoblauch-dip/",
  "https://www.eat-this.org/vegane-zucchinipuffer/",
  "https://www.eat-this.org/veganes-sahne-kirscheis-mit-tonkabohne/",
  "https://www.eat-this.org/wassermelonen-gazpacho-mit-basilikum-minze/",
  "https://www.eat-this.org/unsere-vegane-pho/",
  "https://www.eat-this.org/vegane-penne-alla-vodka/",
  "https://www.eat-this.org/vegane-kichererbsen-schoko-brownies/",
  "https://www.eat-this.org/einfache-vegane-pita-brote/",
  "https://www.eat-this.org/veganer-tempeh-cheeseburger-mit-kraeuter-senf-sauce/",
  "https://www.eat-this.org/vegane-brioche-burger-buns/",
  "https://www.eat-this.org/die-einfachsten-rote-linsen-pancakes/",
  "https://www.eat-this.org/reisnudelsalat-mit-limetten-erdnuss-dressing/",
  "https://www.eat-this.org/vegane-french-toast-roll-ups-mit-mazerierten-erdbeeren/",
  "https://www.eat-this.org/spargel-tomaten-und-seitan-medaillons-vom-blech/",
  "https://www.eat-this.org/schnelle-vegane-quesadillas-mit-jackfruit/",
  "https://www.eat-this.org/geroestete-miso-zucchini/",
  "https://www.eat-this.org/schwaebische-vegane-maultaschen/",
  "https://www.eat-this.org/tteokbokki/",
  "https://www.eat-this.org/vegane-mueslimuffins-mit-erdbeeren/",
  "https://www.eat-this.org/vegane-fruehlingsrollen/",
  "https://www.eat-this.org/schnelle-pinke-zwiebel-pickles/",
  "https://www.eat-this.org/vegane-sauce-hollandaise/",
  "https://www.eat-this.org/cremige-spargelpasta-mit-raeuchertofu/",
  "https://www.eat-this.org/perfekte-vegane-kartoffelpuffer/",
  "https://www.eat-this.org/chinesisches-chilioel/",
  "https://www.eat-this.org/veganer-rhabarberkuchen-mit-streuseln/",
  "https://www.eat-this.org/no-fish-burger-mit-veganer-remoulade/",
  "https://www.eat-this.org/veganes-rucola-baerlauch-pesto/",
  "https://www.eat-this.org/vegane-pide-mit-spinat/",
  "https://www.eat-this.org/schnelle-gebratene-udon-nudeln/",
  "https://www.eat-this.org/veganer-mettigel/",
  "https://www.eat-this.org/unser-liebster-veganer-hefezopf/",
  "https://www.eat-this.org/vegane-karotten-brokkoli-quiche/",
  "https://www.eat-this.org/vegane-wuerstchen-im-schlafrock/",
  "https://www.eat-this.org/szechuan-pilz-scallops-in-knoblauch-sauce/",
  "https://www.eat-this.org/blumenkohl-nudelauflauf/",
  "https://www.eat-this.org/koreanischer-geschmorter-tofu-dubu-jorim/",
  "https://www.eat-this.org/kimchi-kartoffel-eintopf/",
  "https://www.eat-this.org/vegane-cig-koefte/",
  "https://www.eat-this.org/vegane-baked-feta-pasta/",
  "https://www.eat-this.org/einfache-vegane-zwiebelsauce/",
  "https://www.eat-this.org/vegane-baozi-mit-barbecue-tofu-fuellung/",
  "https://www.eat-this.org/die-einfachste-und-leckerste-glasnudelsuppe/",
  "https://www.eat-this.org/gnocchi-pfanne-mit-rosenkohl-und-getrockneten-tomaten/",
  "https://www.eat-this.org/veganes-seitan-schnitzel-wiener-art/",
  "https://www.eat-this.org/vegane-kimchi-spaetzle/",
  "https://www.eat-this.org/spaghetti-mit-zitronen-knoblauch-sauce-und-pilz-scallops/",
  "https://www.eat-this.org/instant-porridge-easy-und-guenstig-selbst-gemacht/",
  "https://www.eat-this.org/rauchiger-eintopf-mit-black-eyed-peas/",
  "https://www.eat-this.org/veganes-gelbes-thai-curry/",
  "https://www.eat-this.org/veganes-bier-fondue-mit-kuerbis/",
  "https://www.eat-this.org/nuss-brownies-mit-gebrannten-haselnuessen/",
  "https://www.eat-this.org/veganer-americano-unser-liebster-aperitif-cocktail/",
  "https://www.eat-this.org/schwarzwurzelgemuese-mit-geroesteten-pinienkernen/",
  "https://www.eat-this.org/kohlrouladen-mit-kuerbis-nuss-fuellung/",
  "https://www.eat-this.org/blaetterteig-canapes-mit-karamellisierten-zwiebeln/",
  "https://www.eat-this.org/herzhaftes-monkey-bread-mit-sauerteig/",
  "https://www.eat-this.org/gruenkernrisotto-mit-kraeuterseitlingen-und-radicchio/",
  "https://www.eat-this.org/vegane-franzoesische-zwiebelsuppe/",
  "https://www.eat-this.org/vegane-schwarzwalder-kirschtorte/",
  "https://www.eat-this.org/limetten-koriander-reis-bowl-mit-suess-saurem-krautsalat/",
  "https://www.eat-this.org/kuerbis-roesti-mit-cashew-miso-dip/",
  "https://www.eat-this.org/vegane-karamellplaetzchen/",
  "https://www.eat-this.org/vegane-wan-tan-suppe/",
  "https://www.eat-this.org/kuerbis-linsen-salat-mit-5-zutaten/",
  "https://www.eat-this.org/veganes-cassoulet-franzoesischer-bohneneintopf/",
  "https://www.eat-this.org/schnelle-gruenkohlpfanne-mit-getrockneten-tomaten/",
  "https://www.eat-this.org/veganer-flammkuchen/",
  "https://www.eat-this.org/veganer-maulwurfkuchen-aber-bitte-mit-sahne/",
  "https://www.eat-this.org/vegane-champignoncremesuppe/",
  "https://www.eat-this.org/vegane-gulaschsuppe/",
  "https://www.eat-this.org/vegane-vollkornwaffeln-mit-kiwi-quark/",
  "https://www.eat-this.org/veganer-kuerbis-nudelauflauf/",
  "https://www.eat-this.org/einfacher-gemuesereis-aus-dem-ofen/",
  "https://www.eat-this.org/veganer-gebratener-reis/",
  "https://www.eat-this.org/vegane-fish-and-chips/",
  "https://www.eat-this.org/das-einfachste-und-leckerste-kohlrabigemuese/",
  "https://www.eat-this.org/vegane-piroggen-mit-kartoffeln-sauerkraut-und-pilzen/",
  "https://www.eat-this.org/vegan-beef-and-broccoli-brokkoli-stir-fry-mit-seitan/",
  "https://www.eat-this.org/falafelsalat-mit-tahin-dressing/",
  "https://www.eat-this.org/vegane-chocolate-chip-cookies/",
  "https://www.eat-this.org/veganes-focaccia-mit-kirschtomaten-oliven-und-getrockneten-feigen/",
  "https://www.eat-this.org/sommerliche-regenbogen-gemueselasagne/",
  "https://www.eat-this.org/vegane-tandoori-seitan-grillspiesse/",
  "https://www.eat-this.org/vegane-gruene-paella-mit-bohnen-erbsen-und-zuckerschoten/",
  "https://www.eat-this.org/gefuellte-zucchinischiffchen-mit-veganem-hackfleisch/",
  "https://www.eat-this.org/vegane-after-eight-eiscreme/",
  "https://www.eat-this.org/pinke-radieschen-gazpacho-mit-mandeln/",
  "https://www.eat-this.org/veganer-heidelbeerkuchen-mit-streuseln/",
  "https://www.eat-this.org/geschmorter-mangold-auf-tahin-zitronen-joghurt/",
  "https://www.eat-this.org/skordalia-griechischer-kartoffel-knoblauch-dip/",
  "https://www.eat-this.org/banh-trang-tron-vietnamesischer-reispapiersalat/",
  "https://www.eat-this.org/pide-mit-veganem-hackfleisch/",
  "https://www.eat-this.org/imam-bayildi-tuerkische-geschmorte-auberginen/",
  "https://www.eat-this.org/perfekte-vegane-pizza/",
  "https://www.eat-this.org/tapiokapudding-mit-basilikum-kiwimus/",
  "https://www.eat-this.org/kichererbsen-frittata-mit-gruenem-spargel/",
  "https://www.eat-this.org/gefuellte-muschelnudeln-mit-raeuchertofu-und-spinat/",
  "https://www.eat-this.org/veganer-kaesekuchen-ohne-boden/",
  "https://www.eat-this.org/bombay-potatoes-masala-aloo/",
  "https://www.eat-this.org/vegane-koettbullar/",
  "https://www.eat-this.org/vegane-spaetzle/",
  "https://www.eat-this.org/veganes-hackfleisch/",
  "https://www.eat-this.org/veganes-risotto-mit-geroestetem-spargel/",
  "https://www.eat-this.org/veganes-bananenbrot-mit-tahin-sesam-swirl/",
  "https://www.eat-this.org/curry-blaetterteigschnecken/",
  "https://www.eat-this.org/karamellisierter-lauch-mit-cacio-e-pepe-hirse/",
  "https://www.eat-this.org/geroesteter-karottenhummus/",
  "https://www.eat-this.org/veganer-schokoladen-babka/",
  "https://www.eat-this.org/veganes-kimchi-grilled-cheese-sandwich/",
  "https://www.eat-this.org/veganer-linseneintopf/",
  "https://www.eat-this.org/zitronen-reissuppe-mit-baerlauch-oel/",
  "https://www.eat-this.org/blumenkohlsteaks-mit-chili-walnuss-topping/",
  "https://www.eat-this.org/ful-medames-aegyptische-bohnen-auf-tahin/",
  "https://www.eat-this.org/vegane-leberwurst/",
  "https://www.eat-this.org/vegane-lasagnesuppe/",
  "https://www.eat-this.org/einfache-kartoffelfrikadellen-mit-buchweizen/",
  "https://www.eat-this.org/vegane-krapfen/",
  "https://www.eat-this.org/veganes-seitan-frikassee/",
  "https://www.eat-this.org/veganes-korma-mit-mohn-kokosjoghurt/",
  "https://www.eat-this.org/cannelloni-mit-artischocken-walnuss-fuellung/",
  "https://www.eat-this.org/veganes-japchae-koreanische-glasnudeln/",
  "https://www.eat-this.org/chia-porridge-mit-kardamom-birnen/",
  "https://www.eat-this.org/chinesische-vegane-pekingsuppe/",
  "https://www.eat-this.org/geroestete-shiitake-auf-miso-steckruebenpueree/",
  "https://www.eat-this.org/veganes-bayrisch-kraut-mit-raeuchertofu/",
  "https://www.eat-this.org/kuerbis-reis-eintopf-mit-gruenkohl/",
  "https://www.eat-this.org/veganer-whiskey-sour-mit-apfelsirup/",
  "https://www.eat-this.org/vegane-ravioli-mit-kuerbisfuellung-salbeibutter/",
  "https://www.eat-this.org/vegane-creme-brulee-tarte-mit-spekulatiusboden/",
  "https://www.eat-this.org/apfel-rotkohl-mit-feigen/",
  "https://www.eat-this.org/vegane-semmelknoedel/",
  "https://www.eat-this.org/seitan-rollbraten-mit-veganer-bacon-kruste/",
  "https://www.eat-this.org/fenchel-selleriesuppe/",
  "https://www.eat-this.org/veganer-soft-cake/",
  "https://www.eat-this.org/graupenrisotto-mit-geroesteten-rotkohlspalten/",
  "https://www.eat-this.org/vegane-ramen-nudeln/",
  "https://www.eat-this.org/saftige-lebkuchenriegel-mit-datteln-tonkabohne/",
  "https://www.eat-this.org/vollkornbrot-mit-frisch-gemahlenem-roggen-weizen/",
  "https://www.eat-this.org/veganer-brokkoli-auflauf-mit-braunem-reis/",
  "https://www.eat-this.org/suesskartoffel-toasts-mit-bimi-brokkoli-und-weissen-bohnen/",
  "https://www.eat-this.org/karotten-kokos-kuerbissuppe-mit-microgreens/",
  "https://www.eat-this.org/tahinkekse-mit-kardamom-und-pistazien/",
  "https://www.eat-this.org/veganer-mapo-tofu/",
  "https://www.eat-this.org/kuerbisaufstrich-mit-sesam-und-chili/",
  "https://www.eat-this.org/veganer-naked-cake-mit-haselnuss/",
  "https://www.eat-this.org/vegane-schupfnudeln/",
  "https://www.eat-this.org/one-pot-reispfanne-mit-kuerbis/",
  "https://www.eat-this.org/veganes-gulasch-mit-jackfruit/",
  "https://www.eat-this.org/vegane-weisswurst-aus-tofu-und-seitan/",
  "https://www.eat-this.org/einfacher-veganer-apfelkuchen-mit-streuseln/",
  "https://www.eat-this.org/selbst-gemachter-veganer-nudelteig/",
  "https://www.eat-this.org/die-beste-vegane-carbonara-mit-kuerbis/",
  "https://www.eat-this.org/chinesische-fruehlingszwiebel-pancakes/",
  "https://www.eat-this.org/erdnusscurry-mit-geroesteten-auberginen/",
  "https://www.eat-this.org/veganes-heidelbeer-semifreddo/",
  "https://www.eat-this.org/blaetterteig-tomaten-galette/",
  "https://www.eat-this.org/iced-chai-latte/",
  "https://www.eat-this.org/vegane-marillenknoedel/",
  "https://www.eat-this.org/pastasalat-mit-geroesteten-tomaten-veganem-mozzarella/",
  "https://www.eat-this.org/gedaempfter-pak-choi-mit-knoblauch-ingwer-sauce/",
  "https://www.eat-this.org/veganes-ceviche-mit-pilzen/",
  "https://www.eat-this.org/veganer-zucchini-schokokuchen/",
  "https://www.eat-this.org/rigatoni-mit-geschmorter-zucchini-und-chili/",
  "https://www.eat-this.org/kalte-kimchi-nudeln-bibim-guksu/",
  "https://www.eat-this.org/unsere-liebste-chili-essig-sauce/",
  "https://www.eat-this.org/no-bake-mango-cake/",
  "https://www.eat-this.org/bun-chay-vietnamesischer-reisnudelsalat/",
  "https://www.eat-this.org/nem-chay-vietnamesische-fruehlingsrollen/",
  "https://www.eat-this.org/curtido-fermentierter-krautsalat-aus-el-salvador/",
  "https://www.eat-this.org/gruene-gazpacho-mit-erbsen-microgreens/",
  "https://www.eat-this.org/switchel-mit-ingwer-erdbeeren/",
  "https://www.eat-this.org/gegrillter-cesar-salat-mit-senf-sourcream-dressing/",
  "https://www.eat-this.org/vegane-spare-ribs-mit-senf-dry-rub/",
  "https://www.eat-this.org/beyond-possible-burger/",
  "https://www.eat-this.org/schnelles-one-pot-quinoa-chili/",
  "https://www.eat-this.org/no-food-waste-radieschensalat/",
  "https://www.eat-this.org/karottensuppe-mit-weissen-bohnen-und-zatar/",
  "https://www.eat-this.org/zatar-gewuerzmischung/",
  "https://www.eat-this.org/vegane-sesamnudeln-mit-spargel-und-pilzen/",
  "https://www.eat-this.org/chapatis-mit-vollkornmehl/",
  "https://www.eat-this.org/punjabi-chana-masala/",
  "https://www.eat-this.org/das-leckerste-kichererbsensalat-sandwich/",
  "https://www.eat-this.org/schnelle-einfache-suesskartoffelpuffer/",
  "https://www.eat-this.org/tofu-vom-blech-mit-spargel-neuen-kartoffeln/",
  "https://www.eat-this.org/rauchiger-seitanaufschnitt/",
  "https://www.eat-this.org/galette-mit-rhabarber-buchweizen/",
  "https://www.eat-this.org/spanakopita-griechischer-spinatstrudel/",
  "https://www.eat-this.org/sabich-israelisches-fruehstuecks-sandwich/",
  "https://www.eat-this.org/poke-bowl-mit-rote-bete/",
  "https://www.eat-this.org/die-besten-roestzwiebeln/",
  "https://www.eat-this.org/socca-mit-fruehlingssalat-und-orangen-vinaigrette/",
  "https://www.eat-this.org/mujadarra-die-leckersten-arabischen-linsen-mit-reis/",
  "https://www.eat-this.org/kichererbsen-tofu-shan-tofu/",
  "https://www.eat-this.org/buchweizen-granola-mit-ahornsirup-und-kardamom/",
  "https://www.eat-this.org/das-einfachste-vegane-kartoffelgratin/",
  "https://www.eat-this.org/vegane-berliner-aus-dem-ofen/",
  "https://www.eat-this.org/linsen-dal-basisrezept/",
  "https://www.eat-this.org/einfaches-wurzelbrot/",
  "https://www.eat-this.org/nordische-erbsensuppe-mit-geroesteten-perlzwiebeln/",
  "https://www.eat-this.org/tofu-kung-pao/",
  "https://www.eat-this.org/cremiger-griessbrei-mit-mandarinensauce/",
  "https://www.eat-this.org/protein-stullen-mit-pilz-bacon-und-gruenkohl/",
  "https://www.eat-this.org/sauerkrautsuppe-mit-weissen-riesenbohnen-und-gruenkohl/",
  "https://www.eat-this.org/weisse-riesenbohnen-deluxe-fuer-dein-meal-prep/",
  "https://www.eat-this.org/teriyaki-tofu-meatballs/",
  "https://www.eat-this.org/vegane-pasta-aus-dem-pastamaker/",
  "https://www.eat-this.org/spaghetti-napoli-pasta-al-pomodoro/",
  "https://www.eat-this.org/goldene-milch/",
  "https://www.eat-this.org/loaded-hummus-mit-geroestetem-blumenkohl/",
  "https://www.eat-this.org/curry-kokos-linsensuppe-mit-spinat/",
  "https://www.eat-this.org/veganer-gin-sour-mit-mandarine-und-zimt/",
  "https://www.eat-this.org/in-cider-geschmorte-aepfel-mit-fruechtebrot-crumble/",
  "https://www.eat-this.org/rotkohl-steaks-mit-misobutter-und-knoblauchchips/",
  "https://www.eat-this.org/das-cremigste-vegane-selleriepueree/",
  "https://www.eat-this.org/pilzgulasch-a-la-bourguignonne/",
  "https://www.eat-this.org/buchweizen-blinis-mit-rote-bete-meerrettich-creme-gin-karottenlachs/",
  "https://www.eat-this.org/veganer-quarkstollen-mit-dattel-marzipan/",
  "https://www.eat-this.org/kuerbisschnitzel-mit-thymian-senf-kruste-und-sellerie-fenchel-salat/",
  "https://www.eat-this.org/ofen-polenta-mit-geroestetem-rosenkohl/",
  "https://www.eat-this.org/strazzate-die-besten-mandel-schokokekse/",
  "https://www.eat-this.org/knusprige-potato-cakes-mit-pilzfuellung-frischem-dill/",
  "https://www.eat-this.org/tempeh-selber-machen/",
  "https://www.eat-this.org/smashed-potatoes-mit-harissa-joghurt-microgreens/",
  "https://www.eat-this.org/rote-bete-pasta-from-hell/",
  "https://www.eat-this.org/tofu-palak-paneer/",
  "https://www.eat-this.org/sauerteig-zwiebelbrot-mit-kuerbis/",
  "https://www.eat-this.org/herbstsalat-mit-next-level-walnuss-miso-dressing/",
  "https://www.eat-this.org/bami-goreng-mit-brokkoli-und-tempeh/",
  "https://www.eat-this.org/porridge-grundrezept/",
  "https://www.eat-this.org/kanelbullar-schwedische-zimtschnecken-mit-pumpkin-spice/",
  "https://www.eat-this.org/unsere-liebste-nussbutter/",
  "https://www.eat-this.org/kuerbis-chili-mit-braunen-linsen-und-pumpkin-spice/",
  "https://www.eat-this.org/gemuese-fermentieren/",
  "https://www.eat-this.org/japanisches-curry-mit-kuerbis/",
  "https://www.eat-this.org/shakshuka-mit-veganem-ei/",
  "https://www.eat-this.org/masala-dal-vada-indische-kichererbsenbaellchen-mit-minz-chutney/",
  "https://www.eat-this.org/geroesteter-brokkoli-mit-gruenen-linsen-und-ras-el-hanout/",
  "https://www.eat-this.org/veganer-pflaumenkuchen-mit-quark-oelteig-vom-blech/",
  "https://www.eat-this.org/das-beste-tomatenbrot-der-welt/",
  "https://www.eat-this.org/einfaches-veganes-fladenbrot/",
  "https://www.eat-this.org/melonen-agua-fresca-mit-galiamelone-chiasamen/",
  "https://www.eat-this.org/gegrillter-fenchel-mit-labneh-und-oliven-kraeuter-pesto/",
  "https://www.eat-this.org/veganer-no-bake-kokos-limettenkuchen-mit-kiwi/",
  "https://www.eat-this.org/baba-ganoush-orientalischer-auberginensalat/",
  "https://www.eat-this.org/vegane-toast-rollups-mit-trockenpflaumen-schokofuellung/",
  "https://www.eat-this.org/thai-reisnudeln-mit-erdnusssauce/",
  "https://www.eat-this.org/gelbe-mais-gazpacho-mit-paprika/",
  "https://www.eat-this.org/die-sechs-leckersten-reisbeilagen/",
  "https://www.eat-this.org/hummus-mit-gegrilltem-gemuese/",
  "https://www.eat-this.org/avocado-fries-aus-dem-airfryer/",
  "https://www.eat-this.org/veganes-naan-brot/",
  "https://www.eat-this.org/gebackene-falafel-mit-sesam/",
  "https://www.eat-this.org/tofu-tikka-masala/",
  "https://www.eat-this.org/carrot-dogs/",
  "https://www.eat-this.org/fermentierter-cashewkaese/",
  "https://www.eat-this.org/spaghetti-mit-veganen-meatballs/",
  "https://www.eat-this.org/vegane-buchweizen-pancakes-mit-mandelmus/",
  "https://www.eat-this.org/vegane-salted-caramel-eiscreme/",
  "https://www.eat-this.org/zoodles-mit-linsenbolognese-ofentomaten/",
  "https://www.eat-this.org/sauerteig-mehrkornbrot-mit-dinkel-und-roggen/",
  "https://www.eat-this.org/blaetterteig-spargelstangen-mit-rotem-pesto/",
  "https://www.eat-this.org/vegane-mandel-panna-cotta-mit-erdbeersauce/",
  "https://www.eat-this.org/seitan-jackfruit-burger-mit-senf-barbecue-sauce/",
  "https://www.eat-this.org/tempeh-sate-mit-erdnuss-dip/",
  "https://www.eat-this.org/naan-pizza-mit-geroestetem-blumenkohl-suesskartoffel-und-pinken-zwiebeln/",
  "https://www.eat-this.org/veganer-eiskaffee-mit-baileys-almande/",
  "https://www.eat-this.org/vollkorn-sauerteigknoten-mit-kuerbis-kraeutern/",
  "https://www.eat-this.org/gefuellte-suesskartoffel-mit-gruenem-spargel-und-baerlauch-chimichurri/",
  "https://www.eat-this.org/veganes-omelette-mit-kichererbsenmehl-baerlauch/",
  "https://www.eat-this.org/edamame-mit-sesam-chili/",
  "https://www.eat-this.org/veganer-rhabarber-erdbeer-crumble-mit-vanillesauce/",
  "https://www.eat-this.org/vegane-vanillesauce/",
  "https://www.eat-this.org/pasta-e-ceci-pasta-mit-kichererbsen/",
  "https://www.eat-this.org/blumenkohl-taboule-mit-rotkraut-geroesteten-kichererbsen/",
  "https://www.eat-this.org/everything-bagel-mit-sauerteig/",
  "https://www.eat-this.org/veganer-karottenkuchen-mit-walnuessen-frischkaesetopping/",
  "https://www.eat-this.org/cremiger-spinat-artischocken-dip/",
  "https://www.eat-this.org/london-fog-earl-grey-latte-mit-vanille/",
  "https://www.eat-this.org/cremige-vegane-rahmchampignons/",
  "https://www.eat-this.org/ribollita-toskanische-gemuesesuppe-mit-schwarzkohl-fenchel/",
  "https://www.eat-this.org/die-besten-veganen-crepes/",
  "https://www.eat-this.org/reisnudel-bowl-mit-krossem-tofu-und-pflaumensauce/",
  "https://www.eat-this.org/veganer-parmesan/",
  "https://www.eat-this.org/curry-blumenkohl-mit-zitronen-raita/",
  "https://www.eat-this.org/bestes-veganes-schoko-bananenbrot/",
  "https://www.eat-this.org/cremiger-schwarze-bohnen-dip-mit-kakao/",
  "https://www.eat-this.org/pinker-couscoussalat-mit-gruenkohl-und-goldmais/",
  "https://www.eat-this.org/vollkornstullen-mit-tempeh-und-kichererbsensalat/",
  "https://www.eat-this.org/capellini-mit-karottengruen-pesto/",
  "https://www.eat-this.org/selleriepfanne-mit-kuerbis-und-kichererbsen/",
  "https://www.eat-this.org/die-besten-veganen-mac-cheese/",
  "https://www.eat-this.org/saftiges-karottenbrot-mit-saaten/",
  "https://www.eat-this.org/schoko-nusspudding-mit-brownie-bites/",
  "https://www.eat-this.org/dinkelbratlinge-mit-gruenem-kartoffelpueree-microgreens/",
  "https://www.eat-this.org/karotten-suesskartoffel-tajine-mit-fenchel-und-weisskraut/",
  "https://www.eat-this.org/goji-ingwer-shot-der-perfekte-after-workout-drink/",
  "https://www.eat-this.org/suesskartoffel-erdnuss-eintopf-mit-linsen-und-kichererbsen/",
  "https://www.eat-this.org/soho-sling-gin-cocktail-mit-thymian/",
  "https://www.eat-this.org/gluehwein-bellini-mit-selbstgemachtem-gluehweinsirup/",
  "https://www.eat-this.org/vegane-pilzterrine-mit-thymian/",
  "https://www.eat-this.org/schokoladen-tartelettes-mit-flor-de-sal-pistazien-granatapfel/",
  "https://www.eat-this.org/beet-wellington-mit-roter-bete-und-duxelles/",
  "https://www.eat-this.org/geroestete-moehren-mit-miso-senf-glasur/",
  "https://www.eat-this.org/wintersalat-mit-portulak-grapefruit/",
  "https://www.eat-this.org/berglinsenaufstrich-mit-getrockneten-tomaten-schalotten/",
  "https://www.eat-this.org/im-ganzen-geroesteter-blumenkohl-mit-weissweinsauce-pilzen/",
  "https://www.eat-this.org/veganer-rotweinkuchen-mit-lebkuchengewuerz/",
  "https://www.eat-this.org/milchreis-mit-vanille-gewuerzter-orangensauce/",
  "https://www.eat-this.org/penne-mit-cremiger-kuerbismarinara-antipasti/",
  "https://www.eat-this.org/kurkuma-good-life-bowl-mit-geroestetem-gemuese-tofu/",
  "https://www.eat-this.org/veganer-versunkener-apfelkuchen-mit-baileys-almande/",
  "https://www.eat-this.org/die-besten-ofenpommes/",
  "https://www.eat-this.org/herzhafte-sauerteigpancakes-mit-pilzen/",
  "https://www.eat-this.org/rote-bete-saft-mit-apfel-ingwer-beet-the-cold/",
  "https://www.eat-this.org/tagliatelle-mit-wirsing-hummussauce/",
  "https://www.eat-this.org/kraeuterpolenta-mit-mangold/",
  "https://www.eat-this.org/herbstliche-crostini-mit-pilzen-und-thymian/",
  "https://www.eat-this.org/kuerbiseintopf-mit-geroestetem-hokkaido-kichererbsen-harissa/",
  "https://www.eat-this.org/herbstliches-ofengemuese-mit-hirse-kuerbiskernoel-dip/",
  "https://www.eat-this.org/herzhafte-galette-mit-apfel-rote-bete-kuerbis/",
  "https://www.eat-this.org/reines-dinkel-sauerteigbrot/",
  "https://www.eat-this.org/spaghetti-aglio-e-olio-mit-oliven-pistazien/",
  "https://www.eat-this.org/kuerbis-suesskartoffel-tajine-mit-couscous-granatapfel/",
  "https://www.eat-this.org/waermende-burrito-bowl-mit-kuerbis-raeuchertofu-tabasco/",
  "https://www.eat-this.org/veganer-obazda/",
  "https://www.eat-this.org/gegrillte-maiskolben-wie-auf-mexikos-strassen/",
  "https://www.eat-this.org/thymian-gemuesepaeckchen-mit-blaubeeren/",
  "https://www.eat-this.org/mung-dal-mit-zucchini/",
  "https://www.eat-this.org/gesunde-thymian-cracker-mit-leinmehl/",
  "https://www.eat-this.org/gruene-gruetze-mit-kiwi/",
  "https://www.eat-this.org/vegane-poke-bowl/",
  "https://www.eat-this.org/fruchtige-mango-popsicles/",
  "https://www.eat-this.org/unser-allerliebster-kartoffelsalat/",
  "https://www.eat-this.org/gruenes-thai-curry-mit-zucchini-auberginen/",
  "https://www.eat-this.org/aprikosenkuchen-mit-olivenoel-mandeln/",
  "https://www.eat-this.org/kohlrabisalat-auf-thailaendische-art-som-tam/",
  "https://www.eat-this.org/basilikum-limonade-mit-limette-ingwer/",
  "https://www.eat-this.org/fusilloni-mit-geroestetem-sommergemuese/",
  "https://www.eat-this.org/weltbester-black-bean-burger/",
  "https://www.eat-this.org/veganer-bacon-aus-reispapier/",
  "https://www.eat-this.org/blitzschnelle-fruchtige-beeren-popsicles/",
  "https://www.eat-this.org/herzhafter-crunchy-trail-mix-und-mit-der-bahn-zum-schloss-neuschwanstein/",
  "https://www.eat-this.org/good-life-bowls-in-5-schritten-zur-perfekten-bowl/",
  "https://www.eat-this.org/geeister-ananas-kokos-mocktail/",
  "https://www.eat-this.org/mutabbal-orientalischer-auberginen-dip/",
  "https://www.eat-this.org/vegane-nicecream-leckeres-gesundes-eis-in-5-minuten/",
  "https://www.eat-this.org/super-knusprige-gebackene-patatas-bravas-mit-mojo-verde/",
  "https://www.eat-this.org/leckerer-fruehstueckssmoothie-mit-apfel-karotte-orangensaft-5-a-day/",
  "https://www.eat-this.org/energy-balls-leckerer-powersnack-mit-viel-protein/",
  "https://www.eat-this.org/schnelle-vegane-pho/",
  "https://www.eat-this.org/stullen-mit-karottenlachs-smorgasbord-vegan/",
  "https://www.eat-this.org/one-pot-spaghetti-alla-puttanesca/",
  "https://www.eat-this.org/vegan-grilled-veggie-sub-aus-vegan-grillen-kann-jeder/",
  "https://www.eat-this.org/gesunde-nachos-mit-kichererbsen-suesskartoffeln-und-frischen-kraeutern/",
  "https://www.eat-this.org/gedaempfte-vegane-dumplings/",
  "https://www.eat-this.org/warmer-buchweizensalat-mit-gruenem-spargel-rucola/",
  "https://www.eat-this.org/veganer-rhabarber-kaesekuchen/",
  "https://www.eat-this.org/pad-thai-mit-gruenem-spargel-und-tofu/",
  "https://www.eat-this.org/knusprige-wuerzige-kurkuma-baguettes/",
  "https://www.eat-this.org/veganer-camembert/",
  "https://www.eat-this.org/vegane-kumpir-mit-paprika-couscous-rotkraut-frischem-rucola/",
  "https://www.eat-this.org/pina-colada-milchreis-mit-erdbeeren/",
  "https://www.eat-this.org/super-gruene-good-life-fruehlingsbowl/",
  "https://www.eat-this.org/veganer-mohn-babka/",
  "https://www.eat-this.org/vegane-sushi-sandwiches-japanische-onigirazu/",
  "https://www.eat-this.org/carrot-cake-bircher-muesli/",
  "https://www.eat-this.org/aloo-gobi-blumenkohl-curry-mit-kartoffeln-kichererbsen/",
  "https://www.eat-this.org/gruene-fruehlingsminestrone-mit-orzo-spargel/",
  "https://www.eat-this.org/schnelles-veganes-vollkornbrot-mit-kuerbiskernmehl/",
  "https://www.eat-this.org/die-perfekte-vegane-linsenbolognese/",
  "https://www.eat-this.org/rote-bete-ketchup/",
  "https://www.eat-this.org/veganes-ruehrei/",
  "https://www.eat-this.org/vegane-jackfruit-tacos-mit-quick-pickles-die-pinterest-idea-journey/",
  "https://www.eat-this.org/pasta-mit-avocado-gruenkohl-pesto/",
  "https://www.eat-this.org/die-fluffigsten-veganen-pancakes-pancake-day-special/",
  "https://www.eat-this.org/polentakuchen-mit-blutorangen-hari-tea/",
  "https://www.eat-this.org/suesskartoffel-pommes-aus-dem-ofen/",
  "https://www.eat-this.org/amaranth-wohlfuehlporridge/",
  "https://www.eat-this.org/kurkuma-elixier-mit-orange-ingwer/",
  "https://www.eat-this.org/hummus-mit-geroesteter-roter-bete/",
  "https://www.eat-this.org/rigatoni-mit-geroestetem-zitronenfenchel/",
  "https://www.eat-this.org/good-life-bowl-mit-broccolini-pinkem-quinoa-crunchy-sesam-tofu/",
  "https://www.eat-this.org/tofu-selber-machen/",
  "https://www.eat-this.org/kohlrabischnitzel-sandwich/",
  "https://www.eat-this.org/porridge-mit-braunem-reis-karamellisierten-zimtbananen/",
  "https://www.eat-this.org/pastaauflauf-mit-pilzen-artischocken/",
  "https://www.eat-this.org/purple-magic-soup/",
  "https://www.eat-this.org/3-gesunde-vegane-instant-snacks-fuer-die-mittagspause-im-buero/",
  "https://www.eat-this.org/veganes-kaesefondue/",
  "https://www.eat-this.org/suesskartoffel-quinoa-sushi-mit-rote-bete-und-feldsalat/",
  "https://www.eat-this.org/veganer-eggnog/",
  "https://www.eat-this.org/veganes-tiramisu-mit-cashew-mascarpone/",
  "https://www.eat-this.org/die-besten-veganen-elisenlebkuchen/",
  "https://www.eat-this.org/raw-mini-cheescake-mit-marzipan-pochierter-chai-birne-weihnachtsmenue-2016/",
  "https://www.eat-this.org/suesskartoffel-strudel-mit-champignons-und-spinat/",
  "https://www.eat-this.org/schwarzwurzelsuppe-mit-glasierten-pilzen-kresse/",
  "https://www.eat-this.org/fettuccine-mit-austernpilzen-thymian/",
  "https://www.eat-this.org/veganer-masala-chai/",
  "https://www.eat-this.org/kartoffel-quinoa-patties/",
  "https://www.eat-this.org/herbstpanzanella-die-glutenfreie-feel-good-box-von-schaer/",
  "https://www.eat-this.org/goldene-milch-hirseporridge-mit-schnellem-bratapfelkompott/",
  "https://www.eat-this.org/sushi-burrito-mit-misoaubergine/",
  "https://www.eat-this.org/kuerbislasagne-mit-spinat-salbei/",
  "https://www.eat-this.org/good-life-kuerbisbowl-mit-linsenquinoa/",
  "https://www.eat-this.org/erbsen-gruenkohlsuppe-mit-chili-limetten-popcorn/",
  "https://www.eat-this.org/heisser-beeren-fruechtepunsch-mit-cranberry-aronia/",
  "https://www.eat-this.org/rettich-dim-sum/",
  "https://www.eat-this.org/bananenbrot-mit-dinkel-dunkler-schokolade/",
  "https://www.eat-this.org/good-life-bibimbap-bowl/",
  "https://www.eat-this.org/vegane-sommerrollen/",
  "https://www.eat-this.org/crostini-mit-caponata/",
  "https://www.eat-this.org/schnelles-kimchi/",
  "https://www.eat-this.org/buchweizensalat-mit-avocado-und-frischen-kraeutern/",
  "https://www.eat-this.org/thai-style-erdnuss-kokos-suppe/",
  "https://www.eat-this.org/double-nut-schoko-popsicles/",
  "https://www.eat-this.org/good-life-falafel-bowl/",
  "https://www.eat-this.org/spargeltacos-mit-maissalsa-und-avocadocrema/",
  "https://www.eat-this.org/kidneybohnen-erdnuss-eintopf/",
  "https://www.eat-this.org/spinat-kichererbsen-curry-mit-kapern/",
  "https://www.eat-this.org/einfache-fruehstuecksmuffins/",
  "https://www.eat-this.org/buchweizen-porridge-mit-kardamom-aprikosensauce/",
  "https://www.eat-this.org/spaghetti-alfredo-mit-cremiger-blumenkohl-sauce/",
  "https://www.eat-this.org/chiapudding-basisrezept/",
  "https://www.eat-this.org/zitronige-wirsingsuppe-mit-graupen/",
  "https://www.eat-this.org/rote-bete-curry/",
  "https://www.eat-this.org/gebackene-barbecue-blumenkohl-bites/",
  "https://www.eat-this.org/cranberry-rosmarin-bennet/",
  "https://www.eat-this.org/vegane-mousse-au-chocolat/",
  "https://www.eat-this.org/geroesteter-roter-rosenkohl-mit-zitrone-und-knoblauch/",
  "https://www.eat-this.org/veganer-szechuan-sellerie-wok/",
  "https://www.eat-this.org/veganer-nussbraten-mit-geschmortem-lauch-und-pilzen/",
  "https://www.eat-this.org/balsamico-glasiertes-wurzelgemuese-mit-cranberries-rosmarin/",
  "https://www.eat-this.org/vegane-bratensauce/",
  "https://www.eat-this.org/cremige-pastinakensuppe/",
  "https://www.eat-this.org/knusprige-schwarzkohl-pies-aus-der-gusseisenpfanne/",
  "https://www.eat-this.org/pimientos-de-padron/",
  "https://www.eat-this.org/glutenfreie-fruehlings-tarte-mit-gruenem-spargel/",
  "https://www.eat-this.org/pilaw-mit-spinat-geroesteten-nuessen/",
  "https://www.eat-this.org/soba-nudeln-mit-schwarzem-pfeffer-gruenkohl-und-tofu/",
  "https://www.eat-this.org/feurige-vegane-seitan-chorizo/",
  "https://www.eat-this.org/veganer-mozzarella/",
  "https://www.eat-this.org/vegane-bratwurst-mit-express-kartoffelsalat/",
  "https://www.eat-this.org/glutenfreie-pizza-tortilla/",
  "https://www.eat-this.org/grapefruit-fizz-alkoholfrei/",
  "https://www.eat-this.org/geroestetes-mandel-zimt-eis-mit-gluehweinpflaumen/",
  "https://www.eat-this.org/gefuellter-seitanbraten-mit-knoblauch-kartoffelpueree/",
  "https://www.eat-this.org/feldsalat-mit-birne-walnuss-orangen-vinaigrette-weihnachtsmenue/",
  "https://www.eat-this.org/sauerkraut-pancakes-mit-pilzrahmsauce/",
  "https://www.eat-this.org/pizza-mit-kraeuterseitlingen-und-viel-knoblauch/",
  "https://www.eat-this.org/veganes-bircher-muesli/",
  "https://www.eat-this.org/veganes-tzatziki/",
  "https://www.eat-this.org/mallorquinischer-mandelkuchen/",
  "https://www.eat-this.org/basic-hummus/",
  "https://www.eat-this.org/pulled-jackfruit-sandwich-mit-selbstgemachter-barbecue-sauce/",
  "https://www.eat-this.org/geschmorte-szechuan-auberginen/",
  "https://www.eat-this.org/vietnamesischer-tomaten-tofu/",
  "https://www.eat-this.org/vegan-iced-coffee/",
  "https://www.eat-this.org/seitan-suess-sauer/",
  "https://www.eat-this.org/conchiglie-mit-geroestetem-gemuese/",
  "https://www.eat-this.org/veganes-saksuka/",
  "https://www.eat-this.org/penne-e-fagioli-bianchi/",
  "https://www.eat-this.org/veganes-grilled-cheese-sandwich/",
  "https://www.eat-this.org/spaghetti-liguria-mit-selbstgemachtem-pesto/",
  "https://www.eat-this.org/veganes-pad-thai/",
  "https://www.eat-this.org/rotes-thai-curry-mit-tofu/",
  "https://www.eat-this.org/veganes-mett/",
  "https://www.eat-this.org/kuerbis-kichererbsencurry/",
  "https://www.eat-this.org/veganes-risotto-mit-pfifferlingen/",
  "https://www.eat-this.org/spaghetti-mit-cremigem-zucchini-ragout/",
  "https://www.eat-this.org/taboule/",
];

const _testUrlsOldRecipes = <String>[
  "https://www.eat-this.org/kuerbispizza-mit-radicchio-und-granatapfel-aus-dem-uuni/",
  "https://www.eat-this.org/vegane-dinkel-laugenstangen-mit-vollkorn/",
  "https://www.eat-this.org/kokoswaffeln-mit-zwetschgen-birnen-kompott/",
  "https://www.eat-this.org/banh-mi-mit-zitronengras-tofu/",
  "https://www.eat-this.org/kaschmir-curry-mit-cashews-garam-masala/",
  "https://www.eat-this.org/veganes-sushi-selber-machen/",
  "https://www.eat-this.org/vegane-vollkorn-bagel-mit-hummus/",
  "https://www.eat-this.org/miso-ramen-mit-mais/",
  "https://www.eat-this.org/camping-chili-mit-dreierlei-bohnen-kaffee/",
  "https://www.eat-this.org/gemuesedoener-mit-aubergine-zucchini-paprika/",
  "https://www.eat-this.org/panzanella/",
  "https://www.eat-this.org/rohes-buchweizen-porridge-mit-maracuja/",
  "https://www.eat-this.org/hummus-wrap-der-perfekte-lunch-snack/",
  "https://www.eat-this.org/veganes-banh-xeo/",
  "https://www.eat-this.org/grilled-veggie-picknick-sandwich/",
  "https://www.eat-this.org/vegane-quark-beerentorte-ohne-backen/",
  "https://www.eat-this.org/griechischer-salat-im-glas-mit-quinoa-oliven-tofu-feta/",
  "https://www.eat-this.org/california-pastasalat/",
  "https://www.eat-this.org/kamut-griessbrei-mit-sommerbeeren/",
  "https://www.eat-this.org/zucchinispaghetti-mit-schwarzem-knoblauch/",
  "https://www.eat-this.org/overnight-oats-mit-frischen-beeren/",
  "https://www.eat-this.org/gegrillte-zucchinipaeckchen-mit-dinkelhack/",
  "https://www.eat-this.org/green-bean-fries-aus-dem-ofen/",
  "https://www.eat-this.org/rote-bete-schoko-cupcakes/",
  "https://www.eat-this.org/quinoaburger-mit-ananas-salsa/",
  "https://www.eat-this.org/veganer-kaesekuchen-mit-provamel/",
  "https://www.eat-this.org/dinkel-artischocken-pizza-mit-rucola/",
  "https://www.eat-this.org/vollkornsandwich-mit-kurkuma-currysalat-24h-in-antwerpen/",
  "https://www.eat-this.org/seitan-burger-mit-ofen-fries/",
  "https://www.eat-this.org/bohnen-wraps-mit-avocado-und-rotkraut/",
  "https://www.eat-this.org/good-life-bowl-mit-glasiertem-tempeh/",
  "https://www.eat-this.org/kichererbsenfladenbrot-mit-zatar/",
  "https://www.eat-this.org/bunte-kartoffeln-mit-mandel-petersilien-pesto/",
  "https://www.eat-this.org/kurkuma-curry/",
  "https://www.eat-this.org/cremige-polenta-mit-austernpilzen/",
  "https://www.eat-this.org/hotpot-auf-japanisch/",
  "https://www.eat-this.org/superfood-pancakes-mit-berlin-organics/",
  "https://www.eat-this.org/rote-bete-puffer-portulak/",
  "https://www.eat-this.org/good-life-bowl-mit-ofengemuese-kurkumadressing/",
  "https://www.eat-this.org/hefezopf-mit-nussfuellung/",
  "https://www.eat-this.org/kuerbis-spinatragout-mit-pistazienreis/",
  "https://www.eat-this.org/porridge-mit-zimt-kakikompott/",
  "https://www.eat-this.org/waermendes-quinoa-porridge-aus-vegan-fruehstuecken-kann-jeder/",
  "https://www.eat-this.org/haselnuss-cupcakes-mit-feigen/",
  "https://www.eat-this.org/kuerbis-donuts-fuer-halloween-schaurige-filmtipps/",
  "https://www.eat-this.org/fruehstuecks-acai-bowl/",
  "https://www.eat-this.org/gruentee-soba-nudeln-mit-zuckerschoten/",
  "https://www.eat-this.org/mafaldine-mit-geroestetem-tomatensugo-pangrattato-belsazar-vermouth/",
  "https://www.eat-this.org/austernpilzschnitzel-mit-wildkraeutersalat-ahornsirup-meerrettich-vinaigrette/",
  "https://www.eat-this.org/portobello-panini-mit-gruenem-erbsen-pesto/",
  "https://www.eat-this.org/acai-goji-superfood-riegel/",
  "https://www.eat-this.org/clean-eating-mango-himbeer-smoothie/",
  "https://www.eat-this.org/rote-bete-farro-bowl-mit-schwarzer-pfeffer-dressing/",
  "https://www.eat-this.org/superfood-popsicles-mit-himbeere-chia/",
  "https://www.eat-this.org/bester-after-workout-shake/",
  "https://www.eat-this.org/cashew-frischkaese-mit-meerrettich/",
  "https://www.eat-this.org/rohe-karotten-spaghetti-mit-cremiger-tahin-sauce/",
  "https://www.eat-this.org/buchweizen-wraps-mit-limetten-quinoa-kraeutertofu-mit-den-edeka-vegan-bio-produkten/",
  "https://www.eat-this.org/fruchtige-chili-gazpacho/",
  "https://www.eat-this.org/superfood-smoothie-bowl/",
  "https://www.eat-this.org/matcha-frappucino/",
  "https://www.eat-this.org/schwedischer-beerenkuchen-mit-mohn/",
  "https://www.eat-this.org/bohnen-meerrettich-hummus-mit-geroestetem-knoblauch/",
  "https://www.eat-this.org/gruener-spargel-in-leichter-tomatensauce-auf-algen-pasta/",
  "https://www.eat-this.org/pizza-mit-sommergemuese-auf-glutenfreier-blumenkohl-crust/",
  "https://www.eat-this.org/holundersirup-mit-agavendicksaft/",
  "https://www.eat-this.org/leckere-tacos-mit-frischem-gemuse-und-meerrettich-sour-cream/",
  "https://www.eat-this.org/alblinsen-spargel-salat/",
  "https://www.eat-this.org/kraut-spaetzle-mit-raeuchertofu-tomaten-7xregional/",
  "https://www.eat-this.org/fruehstuecks-smoothie-mit-ananas-mango/",
  "https://www.eat-this.org/vanille-rhabarberkompott-mit-kardamom/",
  "https://www.eat-this.org/leichte-fruehlingssuppe-mit-spargel-baerlauch/",
  "https://www.eat-this.org/puy-linsen/",
  "https://www.eat-this.org/quinoa-detox-bowl-mit-spinat-hummus/",
  "https://www.eat-this.org/fenchelsalat-mit-linsengemuse/",
  "https://www.eat-this.org/wach-auf-matcha-kekse/",
  "https://www.eat-this.org/mason-jar-salat/",
  "https://www.eat-this.org/kartoffel-zwiebel-roesti-mit-kraeuterjoghurt/",
  "https://www.eat-this.org/barbecue-tofu-sandwich/",
  "https://www.eat-this.org/vegane-burrito-bowl/",
  "https://www.eat-this.org/winter-gluecksrollen/",
  "https://www.eat-this.org/saftiger-haselnusskuchen/",
  "https://www.eat-this.org/chinesisches-five-spice-sojahack/",
  "https://www.eat-this.org/pizza-margherita-vegan-glutenfrei/",
  "https://www.eat-this.org/death-chocolate-raw-chocolate-cake/",
  "https://www.eat-this.org/detox-lemonade/",
  "https://www.eat-this.org/chia-zitronen-muffins/",
  "https://www.eat-this.org/franzoesische-mini-pies-mit-ratatouille-gemuese/",
  "https://www.eat-this.org/mini-tarte-flambees/",
  "https://www.eat-this.org/cremige-lauchsuppe/",
  "https://www.eat-this.org/fusilli-mit-kuerbis-spinat-ragout/",
  "https://www.eat-this.org/tagliatelle-mit-paprikasauce/",
  "https://www.eat-this.org/indisches-dal/",
  "https://www.eat-this.org/italienischer-farro-mit-gruenkohl-und-kichererbsen/",
  "https://www.eat-this.org/asiatischer-blumenkohl-salat/",
  "https://www.eat-this.org/veganes-fruechtebrot/",
  "https://www.eat-this.org/cashew-kaese-dip/",
  "https://www.eat-this.org/pad-thai-salat-mit-mangold/",
  "https://www.eat-this.org/thai-wirsingpaeckchen/",
  "https://www.eat-this.org/geroestete-kichererbsen/",
  "https://www.eat-this.org/linsen-tacos-mit-tahin-joghurt-dip-und-rucola/",
  "https://www.eat-this.org/frozen-joghurt-mit-kirschenmichel-crumble/",
  "https://www.eat-this.org/serviettenknoedel-mit-rahm-pfifferlingen-aus-vegane-lieblingskueche/",
  "https://www.eat-this.org/apfel-pite-aus-vegane-lieblingskueche/",
  "https://www.eat-this.org/maultaschensalat/",
  "https://www.eat-this.org/vegane-pesto-kaesespaetzle/",
  "https://www.eat-this.org/pak-choi-austernpilz-wok/",
  "https://www.eat-this.org/suesskartoffel-kokossuppe-mit-chilitofu/",
  "https://www.eat-this.org/mediterraner-gemusestrudel/",
  "https://www.eat-this.org/veganes-bibimbap/",
  "https://www.eat-this.org/breakfast-sandwich/",
  "https://www.eat-this.org/mango-chutney-mit-crunchy-erdnuss-tofu/",
  "https://www.eat-this.org/wassermelonen-slush/",
  "https://www.eat-this.org/bohnensalat-auf-persische-art/",
  "https://www.eat-this.org/pastasalat-mit-conchiglioni-und-geduenstetem-gemuese/",
  "https://www.eat-this.org/carrot-cake-mit-cashew-lemon-frosting/",
  "https://www.eat-this.org/makkaroni-mit-ingwer-zitronen-marinara/",
  "https://www.eat-this.org/okraschoten-gemuese-mit-couscous/",
  "https://www.eat-this.org/wuerziger-spinat-auf-reisnudeln/",
  "https://www.eat-this.org/veganes-osterbrot/",
  "https://www.eat-this.org/gerostete-kurbisspalten-mit-feldsalat-zitronenvinaigrette/",
  "https://www.eat-this.org/fattoush-orientalischer-salat-mit-geroestetem-brot/",
  "https://www.eat-this.org/szechuan-seitan/",
  "https://www.eat-this.org/avocado-mayonnaise/",
  "https://www.eat-this.org/vincent-vegans-quarterpounder/",
  "https://www.eat-this.org/deftige-mini-tartlettes/",
  "https://www.eat-this.org/fruehstuecks-pancakes/",
  "https://www.eat-this.org/thai-reispudding-mit-mangopuree/",
  "https://www.eat-this.org/wurziger-azuki-bohnen-reissalat/",
  "https://www.eat-this.org/veggie-tray-bake/",
  "https://www.eat-this.org/vanilleeis-rhabarberkompott/",
  "https://www.eat-this.org/pina-colada-eiscreme/",
  "https://www.eat-this.org/veganes-chicken-style-sandwich/",
  "https://www.eat-this.org/mit-couscous-gefuellte-zucchini-und-baerlauch-pesto/",
  "https://www.eat-this.org/tagliatelle-mit-grunem-spargel-thai-basilikum-pesto/",
  "https://www.eat-this.org/tiroler-gewurzbrotchen/",
  "https://www.eat-this.org/spaghetti-catalogna/",
  "https://www.eat-this.org/st-paddys-stew/",
  "https://www.eat-this.org/crunchy-leinsamen-cracker/",
  "https://www.eat-this.org/spitzkrautsalat-mit-grunem-curry-dressing/",
  "https://www.eat-this.org/glasierter-chili-tofu-suesskartoffel/",
  "https://www.eat-this.org/sojaschnitzel-mit-pilzrahmsauce-petersilienkartoffeln/",
  "https://www.eat-this.org/gruener-smoothie/",
  "https://www.eat-this.org/andalusischer-karottensalat/",
  "https://www.eat-this.org/pinkes-pitabrot-mit-zweierlei-dips-goji-topping/",
  "https://www.eat-this.org/vegane-lasagne-bolognese/",
  "https://www.eat-this.org/veggie-curry-mit-kichererbsenkuchlein/",
  "https://www.eat-this.org/power-winter-salat-mit-avocadodressing/",
  "https://www.eat-this.org/tuerkische-linsensuppe/",
  "https://www.eat-this.org/marble-cake-muffins/",
  "https://www.eat-this.org/chili-con-tofu/",
  "https://www.eat-this.org/last-minute-silvester-glasnudelsalat/",
  "https://www.eat-this.org/orientalische-wirsing-rouladen/",
  "https://www.eat-this.org/tomaten-gruenkernsuppe/",
  "https://www.eat-this.org/ratatouille/",
  "https://www.eat-this.org/gnocchi-mit-tomaten-cranberry-sauce/",
  "https://www.eat-this.org/spinatstrudel/",
  "https://www.eat-this.org/gefuellte-avocado/",
  "https://www.eat-this.org/sushi/",
  "https://www.eat-this.org/penne-con-verdura/",
];
