[files]
extend-exclude = [
    "resources/langs/de.json",
    "test/recipe_parser_tests/parser_test_files/**/*.json",
]

[default]
extend-ignore-identifiers-re = [
    "bund",
    "Bund",
    "oder",
    "informations",
    "ein",
]
