name: ingredient_collector
description: An app that collects ingredients from recipe websites and combines them into a shopping list.
version: 0.7.0

environment:
  sdk: '3.3.4'
  flutter: '3.19.6'

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.2
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.8.1
  path: ^1.8.2
  path_provider: ^2.1.3
  test_cov_console: ^0.2.2
  shared_preferences: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - resources/imgs/
