name: ingredient_collector
description: A small app which collects ingredients from recipes from different websites and adds them together to create a shopping list
version: 0.1.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  html: ^0.15.1
  http: ^0.13.5
  intl: ^0.18.0
  json_annotation: ^4.7.0
  optional: ^6.1.0+1
  universal_io: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter:
  uses-material-design: true
