name: ingredient_collector
description: A small app which collects ingredients from recipes from different websites and adds them together to create a shopping list
version: 0.1.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
