name: ingredient_collector
description: An app that collects ingredients from recipe websites and combines them into a shopping list.
version: 0.8.0

environment:
  sdk: '3.7.2'
  flutter: '3.29.2'

dependencies:
  easy_localization: ^3.0.7
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  html: ^0.15.5
  http: ^1.3.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  path: ^1.8.2
  path_provider: ^2.1.4
  test_cov_console: ^0.2.2
  shared_preferences: ^2.5.3

dev_dependencies:
  analyzer: ^7.3.0
  build_runner: ^2.4.9
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  freezed: ^3.0.4
  json_serializable: ^6.8.0
  custom_lint: ^0.7.5
  freezed_lint: ^0.0.9
  # dart_code_metrics: ^5.7.2

flutter:
  uses-material-design: true
  assets:
    - resources/langs/
    - resources/imgs/
