name: Build

on:
  pull_request:

env:
  flutter_version: ${{ vars.FLUTTER_VERSION }}
  java_version: ${{ vars.JAVA_VERSION }}
  java_distribution: ${{ vars.JAVA_DISTRIBUTION }}

jobs:
  build-web:
    name: Build release for Web
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Web release
        uses: ./.github/workflows/build-web/
        with:
          flutter_version: ${{ env.flutter_version }}

  build-linux:
    name: Build release for Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build Linux release
        uses: ./.github/workflows/build-linux/
        with:
          flutter_version: ${{ env.flutter_version }}
