name: Release

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

env:
  flutter_version: ${{ vars.FLUTTER_VERSION }}

jobs:
  build-windows-release:
    name: Build release for Windows
    runs-on: windows-latest
    needs: []
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: env.flutter_version
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Windows
        run: flutter build windows

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-artifacts
          path: 'build/windows/runner/Release/**'
          if-no-files-found: error

  build-web-release:
    name: Build release for Web
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: env.flutter_version
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Web
        run: flutter build web --base-href="/ingredient_collector/"

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-release-artifacts
          path: 'build/web/**'
          if-no-files-found: error

  build-android-release:
    name: Build release for Android
    runs-on: ubuntu-latest
    needs: []
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: env.flutter_version
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Android app bundle
        run: flutter build appbundle

      - name: Build for Android apk
        run: flutter build apk

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release-artifacts
          path: |
            build/app/outputs/bundle/release/**
            build/app/outputs/flutter-apk/app-release.apk
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["build-windows-release", "build-web-release", "build-android-release"]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Windows
      - name: Get windows release artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-release-artifacts
          path: windows-release/

      - name: Zip windows build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r windows-release.zip windows-release

      # Web
      - name: Get web release artifact
        uses: actions/download-artifact@v3
        with:
          name: web-release-artifacts
          path: web-release/

      - name: Zip web build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r web-release.zip web-release

      # Android
      - name: Get android release artifact
        uses: actions/download-artifact@v3
        with:
          name: android-release-artifacts
          path: android-release/

      - name: Zip android build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r android-release.zip android-release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-release.zip
            web-release.zip
            android-release.zip

  deploy-web:
    name: Deploy web release on GitHub Pages
    runs-on: ubuntu-latest
    needs: ["release"]
    permissions:
      contents: read
      pages: write
      id-token: write
    concurrency:
      group: "pages"
      cancel-in-progress: true
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Get web release artifact
        uses: actions/download-artifact@v3
        with:
          name: web-release-artifacts
          path: .

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
