name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  check-branch:
    name: Check branch
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.check.outputs.continue }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Check for main branch
        id: "check"
        run: |
          if [[ $(git name-rev --name-only --exclude="tags/*" ${{ github.sha }}) == "remotes/origin/main" ]]; then
            echo "continue release process."
            echo "::set-output name=continue::true"
          else
            echo "release tag on wrong branch."
            echo "::set-output name=continue::false"
          fi

  build-windows-release:
    name: Build release for Windows
    runs-on: windows-latest
    needs: ["check-branch"]
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Windows
        run: flutter build windows

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: windows-release-artifacts
          path: 'build/windows/runner/Release/**'
          if-no-files-found: error

  build-web-release:
    name: Build release for Web
    runs-on: ubuntu-latest
    needs: ["check-branch"]
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Web
        run: flutter build web

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: web-release-artifacts
          path: 'build/web/**'
          if-no-files-found: error

  build-android-release:
    name: Build release for Android
    runs-on: ubuntu-latest
    needs: ["check-branch"]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'
          cache: 'gradle'

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.3.9'
          channel: 'stable'
          cache: true

      - name: Run setup script
        run: bash setup.ps1

      - name: Build for Android app bundle
        run: flutter build appbundle

      - name: Build for Android apk
        run: flutter build apk

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: android-release-artifacts
          path: |
            'build/app/outputs/bundle/release/app-release.aab'
            'build/app/outputs/flutter-apk/app-release.apk'
          if-no-files-found: error

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: ["build-windows-release", "build-web-release", "build-android-release"]
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Windows
      - name: Get windows release artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-release-artifacts
          path: windows-release/

      - name: Zip windows build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r windows-release.zip windows-release

      # Web
      - name: Get web release artifact
        uses: actions/download-artifact@v3
        with:
          name: web-release-artifacts
          path: web-release/

      - name: Zip web build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r web-release.zip web-release

      # Android
      - name: Get android release artifact
        uses: actions/download-artifact@v3
        with:
          name: android-release-artifacts
          path: android-release/

      - name: Zip android build files
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r android-release.zip android-release

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            windows-release.zip
            web-release.zip
            android-release.zip
