name: Script Support Tests

on:
  schedule:
    # Runs every monday at 12 AM
    - cron: "0 12 * * 1"

env:
  flutter_version: ${{ vars.FLUTTER_VERSION }}

jobs:
  test-script-support:
    name: Test if scripts can still parse recipes
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup
        uses: ./.github/workflows/setup/
        with:
          flutter_version: ${{ env.flutter_version }}

      - name: Run script support tests
        run: flutter test --tags="parsing-test" --reporter=github --test-randomize-ordering-seed random
